### ISSUE TITLE
install.sh doesn't really make sense for static sites

### ISSUE THREAD

**Issue by apt1002** [rrthomas/DarkGlass#12]
See Reuben for details.

**Comment by rrthomas** [comment]
I don't, unfortunately, recall exactly what this was about @apt1002, so if you can supply any more details I'd be grateful.

However, from a quick look, there's an obvious problem: we don't really want to install the contents of `cgi-bin` if we're not building a dynamic web site. For that, we should just need to change a config file (currently `web.pl`). However, we do need a running copy of DarkGlass somewhere!

**Comment by apt1002** [comment]
Oh dear! I didn't understand in the first place, or I would have written a proper issue, sorry. I guess this now waits for your next related bug report.

**Comment by rrthomas** [comment]
No worries, I'll close this issue; it's not like there aren't plenty of actual bugs and other problems that need my attention!
