### ISSUE TITLE
New URLs without `?`

### ISSUE THREAD

**Issue by apt1002** [rrthomas/DarkGlass#18]
Problem: URLs with a `?` in them don't work for statically generated sites in general. These are currently used by DarkGlass to specify (for example) the target MIME type to convert the file to. A typical URL is `file:///blog/README.md?convert=text/html`. Consequently, that functionality doesn't work for static sites.

## Tentative idea (tires not kicked)

Redefine the URLs without `?`s. Remove the query parameter, and add a path component with a file extension corresponding to the MIME type, e.g. `file:///blog/README.md/index.html`.

**Comment by rrthomas** [comment]
Revised plan:

* Keep dynamic URLs at they are. We need URL rewriting in any case (#22).
* For static URLs, just replace the file extension. This makes the final URL nicer, and we can turn the potential name clashes into a feature: if for example we would write `foo.html` but it already exists, then assume it's an override, and use the existing `foo.html`.
* The rest will be taken care of by URL rewriting.
