### ISSUE TITLE
Proof-reading

### ISSUE THREAD

**Issue by apt1002** [rrthomas/DarkGlass#4]
![Screenshot_20230815-141256](https://github.com/rrthomas/DarkGlass/assets/2067837/d4120bc1-8ed9-4f7b-90b8-99350992d5b0)

`web.pl.=*.md` is garbled.

"macro" link is broken.

I was hoping that this "organisation" page would show me how to structure my source files and how the built files will come out, but it doesn't.

**Comment by rrthomas** [comment]
Errors fixed, thanks!
