### ISSUE TITLE
Pretty URLs

### ISSUE THREAD

**Issue by apt1002** [rrthomas/DarkGlass#5]
![Screenshot_20230815-144612](https://github.com/rrthomas/DarkGlass/assets/2067837/68d981ab-2082-4350-af58-0d9f46ba522c)

This isn't particularly good advice. There's no need for the Perl script to have a URL. There's a missed opportunity to sanity-check the URL path (e.g. forbid ".." and " "). And there's no need to mess around with URL rewriting.

The Apache directive I'm thinking of is `ScriptAliasMatch`. https://docstore.mik.ua/orelly/weblinux2/apache/ch16_05.htm

**Comment by rrthomas** [comment]
This sounded like a good idea!

Unfortunately, `ScriptAliasMatch` is not allowed in `.htaccess` files (it has the wrong "Context"), and applies to all URLs: it cannot be overridden in subdirectories (I use this to allow "regular" web pages in part of a site).

I don't think an Apache configuration file is a good place to sanity-check URLs.

Note that the rewrite is trivial: there's no substitution, the URL is simply replaced. It effectively does the same as `ScriptAliasMatch`, but has the advantages outlined above: no need to change the system Apache configuration, and can be overridden (again, by the user).

I have simplified the instructions slightly. I think what would be better for simple use would be to bundle a ready-configured Apache with DarkGlass in a Docker image or similar.
