### ISSUE TITLE
Document static site generation

### ISSUE THREAD

**Issue by apt1002** [rrthomas/DarkGlass#6]
The docs have been written from the point of view of using DarkGlass as a CGI script. Since it's now possible to use it as a static site generator, there are a few places in the docs where clarification is needed that you are talking about the source files.

In particular, it is confusing to use `DocumentRoot` to mean the source directory, since that will instead be the build directory.

I don't think it's necessary to change much. Just check every mention of a directory and make the necessary distinction.

**Comment by rrthomas** [comment]
Thanks for this suggestion! Yes, static site generation is new and under-documented.

Looking through the documentation, I think that "Installation" and "Organization" need to be restructured, into a) What's in the DarkGlass Distribution (part of Organization), b) prerequisites, c) how to set up a dynamic site, d) how to set up a static site. For the rest, there should be no further references to a build directory.

**Comment by rrthomas** [comment]
`DocumentRoot` (the variable in `web.pl`) is always the source directory for DarkGlass. I can't see anywhere that contradicts this in the documentation.
